### ISSUE TITLE
Thank you so much and congratulations..!

### ISSUE THREAD

**Issue by mdobydullah** [postalserver/docs#1]
![congrats](https://user-images.githubusercontent.com/13184472/127600595-deafb59a-3a9c-4c8f-a412-357bd1abe380.jpg)

Hello Postal team,

I was searching for this kind of mail server. I love your tool. Thank you for the new docs especially for the Docker doc. I've just installed Postal on CentOS 8 server. It has taken a few minutes.

Please continue to make such a great tool. Best wishes to you, guys.

<img src="https://user-images.githubusercontent.com/13184472/127601124-446eda93-6f44-4e3c-8d9a-3f3866369aa1.png" width="200px">

**Comment by mdobydullah** [comment]
Just check STARTTLS config.

I added this to  postal.yml file.

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /ssl/domain.crt
  tls_private_key_path: /ssl/domain.key
```

Tested with: https://www.gmass.co/smtp-test

Results:
```
<< 250-My capabilities are
<< 250-STARTTLS
<< 250 AUTH CRAM-MD5 PLAIN LOGIN
>> STARTTLS
<< 220 Ready to start TLS
ERROR: An error occurred while attempting to establish an SSL or TLS connection.
```

Failed to send email with TLS. SSL certificate is correct.
